# Generated by Django 3.2.22 on 2023-10-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='room_id',
        ),
    ]
