# Generated by Django 3.2.22 on 2023-10-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20231027_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='room_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
