# Generated by Django 4.2.5 on 2023-10-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('option_type', models.CharField(choices=[('PS', 'Parking Slot'), ('BB', 'Baby Bed')], max_length=2)),
            ],
            options={
                'db_table': 'hotel_options',
            },
        ),
    ]
